import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docsSidebar: [
    {
      type: "category",
      label: "Introduction",
      collapsed: false,
      items: ["introduction/welcome", "introduction/getting-started"],
    },
    {
      type: "category",
      label: "Learning Tracks",
      collapsed: false,
      items: [
        "tracks/overview",
        "tracks/comparison",
        {
          type: "category",
          label: "Specializations",
          items: [
            "tracks/design/index",
            "tracks/hardware/index",
            "tracks/software/index",
            "tracks/ai/index",
            "tracks/systems/index",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Projects",
      collapsed: false,
      items: [
        "projects/overview",
        "projects/os-robots",
        {
          type: "category",
          label: "Core Projects",
          items: [
            "projects/so-101-arm/index",
            "projects/lerobot-training/index",
            "projects/3d-prototyping/index",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Community",
      collapsed: false,
      items: [
        "community/showcase",
        "community/contributing",
        "community/events",
      ],
    },
    // Legacy content - can be removed later
    {
      type: "category",
      label: "Legacy Tutorials",
      collapsed: true,
      items: [
        { type: "autogenerated", dirName: "tutorial-basics" },
        { type: "autogenerated", dirName: "tutorial-extras" },
      ],
    },
  ],
};

export default sidebars;
